- hosts: localhost
  tasks:
  - tower_host:
      name: another_localhost
      inventory: 'DO AWX Test'
      description: "Just a demo of the tower_host module"
      variables:
        ansible_host: 127.0.1.1
