- hosts: localhost
  tasks:
  - tower_host:
      name: another_localhost
      inventory: 'DO AWX Test'
      description: "Just a demo of the tower_host module"
      variables:
        ansible_host: 127.0.1.1
      tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
      tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
      tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
      tower_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') }}"
