- hosts: all
  tasks:
  - shell: 'echo $RANDOM'
    args:
      executable: /bin/bash
    register: random
  - debug:
      msg: "got my random value: {{ random.stdout }}"
  - set_stats:
      data: "{{ stats }}"
        random_val: "{{ random.stdout }}"
    run_once: true
