- hosts: all
  tasks:
  - debug:
      msg: "random values from previous workflow step: {{ random_val }}"
  - debug:
      msg: "random value from previous workflow step: {{ random_val[inventory_hostname] }}"
