- hosts: all
  tasks:
  - shell: 'echo $RANDOM'
    register: random
  - debug:
      msg: "got my random value: {{ random.stdout }}"
  - set_stats:
      data:
        random_val: "{{ random.stdout }}"
