- hosts: all
  tasks:
  - shell: 'echo $RANDOM'
    args:
      executable: /bin/bash
    register: random
  - debug:
      msg: "got my random value: {{ random.stdout }}"
  - set_fact:
      stats:
        random_val: { "{{ inventory_hostname }}": "{{ random.stdout }}" }
  - set_stats:
      data: "{{ stats }}"
